name: Workflow-5

on:
  workflow_dispatch:  

jobs:
  example-job1:
    runs-on: self-hosted
    steps:
      - name: Acquire lock
        id: acquire-lock
        run: |
          LOCK_FILE=/tmp/workflow.lock
          while [ -f $LOCK_FILE ]; do
            echo "Another workflow running. waiting..."
            sleep 10
          done
          touch $LOCK_FILE
      - name: Step 1
        run: |
         echo "This is Workflow 1 - Step 1"
         cat /proc/sys/kernel/hostname
         sleep 60
      - name: Release lock
        if: always()
        run: |
          LOCK_FILE=/tmp/workflow.lock
          rm -f $LOCK_FILE

# name: Workflow 1

# on:
#   workflow_dispatch:

# jobs:
#   lock_job:
#     runs-on: ubuntu-latest
#     outputs:
#       lock_acquired: ${{ steps.lock_status.outputs.lock_acquired }}
#     steps:
#       - name: Acquire lock
#         id: lock_status
#         run: |
#           LOCK_FILE=/tmp/workflow.lock
#           while [ -f $LOCK_FILE ]; do
#             echo "Another workflow is running. Waiting..."
#             sleep 10
#           done
#           touch $LOCK_FILE
#           echo "Lock acquired."
#           echo "::set-output name=lock_acquired::true"

#   job1:
#     runs-on: ubuntu-latest
#     needs: lock_job
#     steps:
#       - name: Step 1
#         run: |
#           echo "This is Workflow 1 - Job 1"
#           sleep 10

#   job2:
#     runs-on: ubuntu-latest
#     needs: [lock_job, job1]
#     steps:
#       - name: Step 2
#         run: |
#           echo "This is Workflow 1 - Job 2"
#           sleep 10

#   job3:
#     runs-on: ubuntu-latest
#     needs: [lock_job, job1]
#     steps:   
#       - name: Step 3
#         run: |
#           echo "This is Workflow 1 - Job 3"
#           sleep 20

#   job4:
#     runs-on: ubuntu-latest
#     needs: [lock_job, job2, job3]
#     steps:     
#       - name: Step 4
#         run: echo "This is Workflow 1 - Job 4"

#   release_lock:
#     runs-on: ubuntu-latest
#     needs: [job4]
#     if: always()
#     steps:
#       - name: Release lock
#         run: |
#           LOCK_FILE=/tmp/workflow.lock
#           rm -f $LOCK_FILE
#           echo "Lock released."

